# Generated by Django 5.2.3 on 2025-06-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('creation_date', models.DateField()),
                ('customer', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=20)),
                ('order_reference', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('salesperson', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primary_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('finance_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('invoice_address', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tell_no', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('lpo_confirmation_date', models.DateField(blank=True, null=True)),
                ('lpo_date', models.DateField(blank=True, null=True)),
                ('lpo_number', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('order_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='SalesOrders.salesorder')),
            ],
        ),
    ]
