# Generated by Django 5.2.3 on 2025-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('creation_date', models.DateField()),
                ('customer', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('order_reference', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('salesperson', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('finance_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('invoice_address', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tell_no', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('lpo_confirmation_date', models.DateField(blank=True, null=True)),
                ('lpo_date', models.DateField(blank=True, null=True)),
                ('lpo_number', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
