# Generated by Django 5.2.3 on 2025-06-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='currency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='finance_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='primary_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tell_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
