# Generated by Django 5.2.3 on 2025-06-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesOrders', '0002_alter_salesorder_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='SalesOrders.salesorders')),
            ],
        ),
    ]
