# Generated by Django 5.2.3 on 2025-06-29 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesOrders', '0003_salesorders_salesorderlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderlines',
            name='order_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='SalesOrders.salesorder'),
        ),
        migrations.DeleteModel(
            name='SalesOrders',
        ),
    ]
