# Generated by Django 5.2.3 on 2025-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesOrders', '0004_alter_salesorderlines_order_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderlines',
            name='margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
